### ISSUE TITLE
Min SDK

### ISSUE THREAD

**Issue by mehdico** [hariprasanths/FloatingToast#1]
Why min sdk is 21? library is completely compatible with sdk 17+.
Actually by changing one line of code it's compatible with sdk 15+.

**Comment by hariprasanths** [comment]
You are welcome to give a PR.

**Comment by owellsky** [comment]
minSDK 21 toast show in leftside? 

how to solve this

**Comment by mehdico** [comment]
Hi,
@owellsky I solve text alignment issue, look following link or wait for my pull request if approved.
[(https://github.com/mehdico/FloatingToast)]

@hariprasanths Please check my pull request.
Thanks

**Comment by hariprasanths** [comment]
The PR has been merged
